name: gunes_saati
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  cloud_firestore: ^5.3.0
  location: ^7.0.0
  http: ^1.2.2
  geocoding: ^3.0.0
  animated_notch_bottom_bar: ^1.0.3
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  firebase_storage: ^12.2.0
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/background.png
    - assets/images/intro1.jpg
    - assets/images/intro2.jpg
    - assets/images/intro3.jpg